// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srqqxvhbzuvfjexvbkbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycXF4dmhienV2ZmpleHZia2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTMwODgsImV4cCI6MjA3Njg4OTA4OH0.Y-7Jvf6hOM13B1SLPIIySMGEb1LFzJuRJhzKuW9DJ3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});